### PR TITLE
Add missing command status description (according to SMMP 3.4) to Neg…

### LINKED ISSUE #76: Add description from SMPP specification to NegativeResponseException error message?
Currently error messages of `NegativeResponseException` return for example `Negative response 0000000b found`.

In my opinion it would be helpful if the error messages included the description from the SMPP specification, e.g. `Negative response 0000000b (Invalid Destination Address) found.`

What do you think?

### PR DESCRIPTION
**Pull request by PascalSchumacher**
…ativeResponseException (closes #76)

Should I also add the description for SMPP 5 status commands?

### CODE REVIEW

**Comment by pmoerenhout** [comment]
Thanks again. I think I will prepare for a new minor release 2.3.6...

**Comment by PascalSchumacher** [comment]
Great. Thank you very much!

**Comment by PascalSchumacher** [comment]
>I think I will prepare for a new minor release 2.3.6...

That would be very much appreciated. It could be included in the next camel release (end of the month).

**Comment by pmoerenhout** [comment]
Release 2.3.6 is now on Maven Central.

**Pull request merged**
