### PR TITLE
CHANGES.txt: most recent changes at the top of the file

### PR DESCRIPTION
**Pull request by PascalSchumacher**
Hi Pim,

I thinks it's more convenient for users if the most recent changes are displayed first, but I guess it's just a matter of personal preferences, so feel free to just close the pull request if you disagree.

Cheers,
Pascal

### CODE REVIEW

**Comment by pmoerenhout** [comment]
Agree.

**Comment by pmoerenhout** [comment]
Hi Pascal, I totally agree! Thanks. I'm want to release 2.2.3 today, so if you have more useful requests.... Regards, Pim

**Comment by PascalSchumacher** [comment]
Hi Pim,

thanks for releasing 2.2.3. https://github.com/opentelecoms-org/jsmpp/pull/22 is my last pull request for today (of course you can also release 2.2.3 without it).

Cheers,
Pascal

**Comment by pmoerenhout** [comment]
Thanks. I just release 2.2.3, so it will show up in Maven Central shortly...

**Pull request merged**
